change CsNumber to CSNumber to avoid lossing CsNumber
bcgov/jag-icon-2 pull request #116
Opened 2023-03-16 21:31 UTC by jianmingtu

2023-03-16 21:33 UTC, sylar-zeyangz requested changes

2023-03-16 21:33 UTC, sylar-zeyangz commented on icon2-common-models/src/main/java/ca/bc/gov/open/icon/utils/XMLUtilities.java
> +                                        .replaceAll("<CsNumber>|<csNumber>|<csNum>", "<CSNumber>")
let's leave csNum out, thanks

2023-03-16 23:46 UTC, jianmingtu commented on icon2-common-models/src/main/java/ca/bc/gov/open/icon/utils/XMLUtilities.java
> +                                        .replaceAll("<CsNumber>|<csNumber>|<csNum>", "<CSNumber>")
removed csNum

2023-03-17 15:23 UTC, KFloodBCGov approved these changes

2023-03-17 15:36 UTC, merged