integrate publishHSR
bcgov/jag-icon-2 pull request #52
Opened 2022-11-03 22:38 UTC by jianmingtu

2022-11-04 18:06 UTC, sylar-zeyangz requested changes

2022-11-04 18:45 UTC, jianmingtu commented on icon-two-common-application-1-1/src/main/java/ca/bc/gov/open/icon/controllers/HealthController.java
> +            var publishHSRResponse = new PublishHSRResponse();
publishHSRResponse is the old response, which returns xml back to front. so,  do not need to change resp to publishHSRResponseDocument

2022-11-04 20:32 UTC, sylar-zeyangz requested changes

2022-11-04 20:32 UTC, sylar-zeyangz commented on icon-two-common-application-1-1/src/main/java/ca/bc/gov/open/icon/controllers/HealthController.java
> +            var publishHSRResponse = new PublishHSRResponse();
no

2022-11-05 00:34 UTC, jianmingtu commented on icon-two-common-application-1-1/src/main/java/ca/bc/gov/open/icon/controllers/HealthController.java
> +            var publishHSRResponse = new PublishHSRResponse();
under the updated implementation,  Kyle wants to move  the init ORDS,  so I am able to get a response from ORDS,  reiterate the result's health-service requests from ORDS to create publishHSRResponseDocument and then build xmlstring.

2022-11-06 20:27 UTC, sylar-zeyangz approved these changes

2022-11-07 16:14 UTC, merged