Feature/readme
bcgov/jag-icon-2 pull request #80
Opened 2022-12-12 23:36 UTC by jianmingtu

2022-12-12 23:40 UTC, sylar-zeyangz requested changes

2022-12-12 23:40 UTC, sylar-zeyangz commented on icon-two-code-coverage/pom.xml
> -        </dependency>
need apps

2022-12-13 17:02 UTC, jianmingtu commented on icon-two-code-coverage/pom.xml
> -        </dependency>
done

2022-12-13 22:16 UTC, sylar-zeyangz approved these changes

2022-12-13 22:18 UTC, merged